# Generated by Django 5.2.1 on 2025-05-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recflix', '0002_playlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=20)),
                ('poster', models.CharField(max_length=255)),
                ('count', models.IntegerField(default=1)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-count', '-last_updated'],
                'unique_together': {('title', 'category')},
            },
        ),
    ]
